jobs:

- name: setStorageBase
  set:
    val: 5

- name: deployStorageK
  deploy:
    contract: storage.sol

- name: setStorage
  call:
    destination: $deployStorageK
    function: set
    data:
      - [1, 2, 3]

- name: queryStorage
  query-contract:
    destination: $deployStorageK
    function: get

- name: assertStorage
  assert:
    key: $queryStorage
    relation: eq
    val: $setStorageBase
